export const FETCH_FIVE_DAY_DATA_SUCCESS = 'WEATHER-APP-CONTAINER/FETCH_FIVE_DAY_DATA_SUCCESS';
export const FETCH_FIVE_DAY_DATA_PENDING = 'WEATHER-APP-CONTAINER/FETCH_FIVE_DAY_DATA_PENDING';
export const FETCH_FIVE_DAY_DATA_REJECT = 'WEATHER-APP-CONTAINER/FETCH_FIVE_DAY_DATA_REJECT';

export const FETCH_CURRENT_WEATHER_DATA_PENDING = 'WEATHER-APP-CONTAINER/FETCH_CURRENT_WEATHER_DATA_PENDING';
export const FETCH_CURRENT_WEATHER_DATA_SUCCESS = 'WEATHER-APP-CONTAINER/FETCH_CURRENT_WEATHER_DATA_SUCCESS';
export const FETCH_CURRENT_WEATHER_DATA_REJECT = 'WEATHER-APP-CONTAINER/FETCH_CURRENT_WEATHER_DATA_REJECT';
